import type { Metadata } from "next";
import { Asimovian, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { toast, Toaster } from "sonner";
import { ThemeToggle } from "@/components/theme-toggle";
import { Providers } from "@/components/Provider";

const asimovian = Asimovian({
  weight: "400",
  variable: "--font-asimovian",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${asimovian.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Providers>
          {children}
          </Providers>
          <div className="top-1 right-2 fixed">
            <ThemeToggle />
          </div>
          <Toaster theme="dark" richColors position="top-right"/>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
